### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/rvl224/OnePose_Plus_Plus-main/data/demo/demo_cam/demo_cam-annotate/color'

### ISSUE THREAD

**Issue by brian2lee** [zju3dv/OnePose_Plus_Plus#39]
I put demo data under repo root, ran:
```
REPO_ROOT=/home/rvl224/OnePose_Plus_Plus-main

ln -s /home/rvl224/OnePose_Plus_Plus-main/demo_cam $REPO_ROOT/data/demo

OBJ_NAME=demo_cam

cd $REPO_ROOT

bash scripts/demo_pipeline.sh $OBJ_NAME
```
But it showed 
```
Error executing job with overrides: ['+preprocess=sfm_demo', 'dataset.data_dir=[/home/rvl224/OnePose_Plus_Plus-main/data/demo/demo_cam demo_cam-annotate]', 'dataset.outputs_dir=/home/rvl224/OnePose_Plus_Plus-main/data/demo/sfm_model']
Traceback (most recent call last):
  File "/home/rvl224/OnePose_Plus_Plus-main/run.py", line 400, in main
    globals()[cfg.type](cfg)
  File "/home/rvl224/OnePose_Plus_Plus-main/run.py", line 65, in sfm
    sfm_worker(data_dirs, cfg)
  File "/home/rvl224/OnePose_Plus_Plus-main/run.py", line 105, in sfm_worker
    img_name_lists = os.listdir(osp.join(seq_dir, img_dir_name))
FileNotFoundError: [Errno 2] No such file or directory: '/home/rvl224/OnePose_Plus_Plus-main/data/demo/demo_cam/demo_cam-annotate/color'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
what did I do wrong? There isn't color in /demo_cam/demo_cam-annotate when I download from onedrive.

**Comment by brian2lee** [comment]
oops, you have to pull the demo_cam out after you extracted it. Since there's a "__MACOSX" folder beside it I thought the whole extracted file belongs in the dataset.

**Comment by Starlit404** [comment]
> oops, you have to pull the demo_cam out after you extracted it. Since there's a "__MACOSX" folder beside it I thought the whole extracted file belongs in the dataset.

hey pal, I met the same problem but I haven't finish it yet.
what do you mean by pulling the demo_cam out? it's still no folder called color in the diretory, right?
appreciate it if you can help me out.
