### ISSUE TITLE
Error while checking the demo

### ISSUE THREAD

**Issue by shivakarnati** [zju3dv/OnePose_Plus_Plus#56]
When I was trying to check the demo for demo_cam object, I am encountering this error. Can someone please help me to resolve?

`bash scripts/demo_pipeline.sh demo_cam
Current work dir: /home/shiva/OnePose_Plus_Plus
-------------------
Parse scanned data:
-------------------
=> Processing test sequence:  demo_cam-test
=> Processing annotate sequence:  demo_cam-annotate
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<00:00, 1602.27it/s]
--------------------------------------------------------------
Run Keypoint-Free SfM to reconstruct object point cloud for pose estimation:
--------------------------------------------------------------
/home/shiva/OnePose_Plus_Plus/run.py:398: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="configs/", config_name="config.yaml")
/home/shiva/miniconda3/envs/oneposeplus/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/shiva/miniconda3/envs/oneposeplus/lib/python3.7/site-packages/hydra/_internal/hydra.py:127: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  configure_logging=with_log_configuration,
2024-03-18 18:33:07.035 | INFO     | __main__:sfm_worker:93 - Worker: 0 will process: ['demo'], total: 1 objects
  0%|                                                                                                                                                      | 0/1 [00:00<?, ?it/s]2024-03-18 18:33:07.036 | INFO     | __main__:sfm_worker:97 - Processing /home/shiva/OnePose_Plus_Plus/data/demo/demo_cam demo_cam-annotate.
[2024-03-18 18:33:08,708][numexpr.utils][INFO] - Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-03-18 18:33:08.823 | INFO     | __main__:sfm_core:193 - Keypoint-Free SfM coarse reconstruction begin...
[2024-03-18 18:33:08,839][pytorch_lightning.utilities.seed][INFO] - Global seed set to 666
  0%|                                                                                                                                                      | 0/1 [00:01<?, ?it/s]
Error executing job with overrides: ['+preprocess=sfm_demo', 'dataset.data_dir=[/home/shiva/OnePose_Plus_Plus/data/demo/demo_cam demo_cam-annotate]', 'dataset.outputs_dir=/home/shiva/OnePose_Plus_Plus/data/demo/sfm_model']
Traceback (most recent call last):
  File "/home/shiva/OnePose_Plus_Plus/run.py", line 400, in main
    globals()[cfg.type](cfg)
  File "/home/shiva/OnePose_Plus_Plus/run.py", line 65, in sfm
    sfm_worker(data_dirs, cfg)
  File "/home/shiva/OnePose_Plus_Plus/run.py", line 129, in sfm_worker
    sfm_core(cfg, img_lists, outputs_dir_root, obj_name)
  File "/home/shiva/OnePose_Plus_Plus/run.py", line 228, in sfm_core
    verbose=cfg.verbose
  File "/home/shiva/OnePose_Plus_Plus/src/KeypointFreeSfM/coarse_match/coarse_match.py", line 148, in detector_free_coarse_matching
    matches = match_worker(dataset, all_ids, cfgs["matcher"], verbose=verbose)
  File "/home/shiva/miniconda3/envs/oneposeplus/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/shiva/OnePose_Plus_Plus/src/KeypointFreeSfM/coarse_match/coarse_match_worker.py", line 46, in match_worker
    matcher = build_model(args['model'])
  File "/home/shiva/OnePose_Plus_Plus/src/KeypointFreeSfM/coarse_match/coarse_match_worker.py", line 21, in build_model
    state_dict = torch.load(args['weight_path'], map_location="cpu")["state_dict"]
  File "/home/shiva/miniconda3/envs/oneposeplus/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/shiva/miniconda3/envs/oneposeplus/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shiva/miniconda3/envs/oneposeplus/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'weight/LoFTR_wsize9.ckpt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
-----------------------------------
Run inference and output demo video:
-----------------------------------
/home/shiva/OnePose_Plus_Plus/demo.py:168: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="configs/", config_name="config.yaml")
/home/shiva/miniconda3/envs/oneposeplus/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/shiva/miniconda3/envs/oneposeplus/lib/python3.7/site-packages/hydra/_internal/hydra.py:127: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  configure_logging=with_log_configuration,
  0%|                                                                                                                                                      | 0/1 [00:00<?, ?it/s]2024-03-18 18:33:11.678 | INFO     | __main__:inference:165 - Eval /home/shiva/OnePose_Plus_Plus/data/demo/demo_cam/demo_cam-test
2024-03-18 18:33:11.683 | INFO     | src.datasets.OnePosePlus_inference_dataset:__init__:38 - Will process:330 images 
  0%|                                                                                                                                                      | 0/1 [00:00<?, ?it/s]
Error executing job with overrides: ['+experiment=inference_demo', 'data_base_dir=/home/shiva/OnePose_Plus_Plus/data/demo/demo_cam demo_cam-test', 'sfm_base_dir=/home/shiva/OnePose_Plus_Plus/data/demo/sfm_model/outputs_softmax_loftr_loftr/demo_cam']
Traceback (most recent call last):
  File "/home/shiva/OnePose_Plus_Plus/demo.py", line 170, in main
    globals()[cfg.type](cfg)
  File "/home/shiva/OnePose_Plus_Plus/demo.py", line 166, in inference
    inference_core(cfg, data_root, seq_dir, sfm_model_dir)
  File "/home/shiva/OnePose_Plus_Plus/demo.py", line 81, in inference_core
    preload=True,
  File "/home/shiva/OnePose_Plus_Plus/src/datasets/OnePosePlus_inference_dataset.py", line 54, in __init__
    avg_anno_3d_path, pad=self.pad, load_3d_coarse=load_3d_coarse
  File "/home/shiva/OnePose_Plus_Plus/src/datasets/OnePosePlus_inference_dataset.py", line 113, in read_anno3d
    avg_data = np.load(avg_anno3d_file)
  File "/home/shiva/miniconda3/envs/oneposeplus/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/shiva/OnePose_Plus_Plus/data/demo/sfm_model/outputs_softmax_loftr_loftr/demo_cam/anno/anno_3d_average.npz'
`

**Comment by anshium** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '$REPO_ROOT/data/demo/sfm_model/outputs_softmax_loftr_loftr/demo_cam/anno/anno_3d_average.npz'

Hi, I am facing the same problem. Did you find a fix?
